### ISSUE TITLE
Problem with pulling images | docker 1.3.0 | OSX

### ISSUE THREAD

**Issue by andidol** [GoogleCloudPlatform/appengine-vm-fortunespeak-python#21]
bash-3.2$ gcloud preview app setup-managed-vms
Select the runtime to download the base image for:
 [1] Go
 [2] Java
 [3] Python27
 [4] All
Please enter your numeric choice (4):  3

Pulling base images for runtimes [python27] from Google Cloud Storage
Pulling image: google/appengine-python27
Traceback (most recent call last):
  File "/Users/andreasdolinsek/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 170, in <module>
    main()
  File "/Users/andreasdolinsek/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 166, in main
    _cli.Execute()
  File "/Users/andreasdolinsek/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 385, in Execute
    post_run_hooks=self.__post_run_hooks, kwargs=kwargs)
  File "/Users/andreasdolinsek/google-cloud-sdk/./lib/googlecloudsdk/calliope/frontend.py", line 274, in _Execute
    pre_run_hooks=pre_run_hooks, post_run_hooks=post_run_hooks)
  File "/Users/andreasdolinsek/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 928, in Run
    result = command_instance.Run(args)
  File "/Users/andreasdolinsek/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/setup_managed_vms.py", line 39, in Run
    args.image_version)
  File "/Users/andreasdolinsek/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/pull.py", line 54, in PullBaseDockerImages
    util.PullSpecifiedImages(docker_client, image_names, version, bucket)
  File "/Users/andreasdolinsek/google-cloud-sdk/./lib/googlecloudsdk/appengine/lib/images/util.py", line 232, in PullSpecifiedImages
    'Error pulling {image}: {e}'.format(image=image_name, e=e))
googlecloudsdk.appengine.lib.images.util.DockerPullError: Error pulling google/appengine-python27: 404 Client Error: Not Found ("No such id: localhost:49153/google/appengine-python27")

**Comment by bavetta** [comment]
This may have been fixed with this commit:
https://github.com/GoogleCloudPlatform/appengine-vm-fortunespeak-python/commit/e3f374dbb98542e9fac483a29f714f9c3d5642c1
